spring.datasource.url=jdbc:mysql://localhost:3306/traveloop
spring.datasource.username=root
spring.datasource.password=Rutuja@23

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081